CFIN-206 add serverless changes due to code review
university-of-york/uoy-app-course-search pull request #10
Opened 2020-09-15 16:04 UTC by ncn1

2020-09-16 14:11 UTC, FergusMcGlynn approved these changes

2020-09-17 08:11 UTC, FergusMcGlynn requested changes

2020-09-17 08:11 UTC, FergusMcGlynn commented on package.json
>      "node-fetch": "^2.6.0",
I know that `node-fetch` was added in a different pull request, but it's not needed by the project, so could we remove it?

2020-09-17 08:27 UTC, FergusMcGlynn commented on package.json
>      "node-fetch": "^2.6.0",
Actually, on second thoughts - I think `node-fetch` will be needed. My mistake - ignore this!

2020-09-17 08:27 UTC, FergusMcGlynn approved these changes

2020-09-17 08:52 UTC, RichardAllum approved these changes

2020-09-17 10:44 UTC, merged