CFIN-445 Add sentence case function to capitalise Undergraduate tag
university-of-york/uoy-app-course-search pull request #110
Opened 2021-03-04 14:24 UTC by ChristianBeddows

2021-03-04 14:26 UTC, ChristianBeddows commented on src/components/CourseDetails.js
> +            <LevelAndAwardTag level={sentenceCase(course.level)} award={course.award} />
Do you think this is the right place to use this function?
I am unsure whether it belongs within the `LevelAndAwardTag` function, similar to how the startYear string manipulation happens within the `StartDateAndLengthTag` function on line 36.

2021-03-04 14:28 UTC, mrgibbonsuoy commented on src/components/CourseDetails.js
> +            <LevelAndAwardTag level={sentenceCase(course.level)} award={course.award} />
I'd agree with your position it keeps it consistent.

2021-03-04 14:29 UTC, mrgibbonsuoy approved these changes

2021-03-04 14:32 UTC, ChristianBeddows commented on src/components/CourseDetails.js
> +            <LevelAndAwardTag level={sentenceCase(course.level)} award={course.award} />
I'm not sure if this is consistent - the function call should perhaps belong on line 23, similar to line 36, further down in this file

2021-03-04 14:36 UTC, ncn1 commented on src/components/CourseDetails.js
> +            <LevelAndAwardTag level={sentenceCase(course.level)} award={course.award} />
Surely it's actually inconsistent - this one done in the _call to_ LevelAndAwardTag
 and startYear string manipulation happens _within_ the StartDateAndLengthTag.
 
 If we are saying the level description in a rich tag should always be in sentence case (which I think we are and was the implication of using css for it), I think it should also be used _within_ LevelAndAwardTag.

2021-03-04 14:38 UTC, ncn1 commented on src/utils/formatting.js
> +const sentenceCase = (string) => {
Nice succinct and clear function!

2021-03-04 14:40 UTC, mrgibbonsuoy commented on src/components/CourseDetails.js
> +            <LevelAndAwardTag level={sentenceCase(course.level)} award={course.award} />
I was thinking about someone opening the project and scanning the files. Whilst out of position you can see at a glance the tags.

2021-03-05 13:34 UTC, ce666-york requested changes
Small point about more tests!

2021-03-05 13:34 UTC, ce666-york commented on src/components/CourseDetails.js
> +            <LevelAndAwardTag level={sentenceCase(course.level)} award={course.award} />
Given it's a `LevelAndAwardTag` rather than a generic `Tag` component, I'd lean towards putting all functionality for rendering this tag correctly within the component. It's really not a problem though.

2021-03-05 13:34 UTC, ce666-york commented on src/tests/utils/formatting.test.js
> +    it("Capitalises the first letter of the input string", async () => {
I'd like to see more tests for edge cases e.g. empty string, null string.

I think it would also be useful to put in tests to show what we expect to see when we receive input that's already in sentence case, input that's completely capitalised, and input with spaces/formatting. Pretend you don't know anything about the implementation details!

2021-03-05 14:00 UTC, FergusMcGlynn commented on src/tests/utils/formatting.test.js
> +    it("Capitalises the first letter of the input string", async () => {
This could probably be [shortened using Jest's `each` function](https://elfi-y.medium.com/reduce-boilerplate-test-code-with-jest-it-each-30a0eec9776d) - like the `where` clause in Spock tests. But it's not a problem how it is currently.

2021-03-05 16:19 UTC, FergusMcGlynn approved these changes

2021-03-05 16:23 UTC, FergusMcGlynn commented on src/components/CourseDetails.js
> +            <LevelAndAwardTag level={sentenceCase(course.level)} award={course.award} />
I'm a little confused - is there any reason not to call `sentenceCase()` in `RichTag`, so that it applies to all text in all tags no matter which type? E.g, in `RichTag.js`:
```
    <li className="rich-tag">                                                                                     
        {topIcon && <i aria-hidden className={`c-icon c-icon--${topIcon} c-icon--2x`} data-testid="tag-icon" />}  
        <p className="rich-tag__title">{sentenceCase(title)}</p>                                                                
        <p className="rich-tag__text">{sentenceCase(subText)}</p>                                                               
    </li>                                                                                                         
```

2021-03-05 16:38 UTC, ce666-york approved these changes

2021-03-08 14:13 UTC, ChristianBeddows commented on src/components/CourseDetails.js
> +            <LevelAndAwardTag level={sentenceCase(course.level)} award={course.award} />
I like the idea of using the function within `RichTag` so that it always applies to text - though following from our discussion earlier I'm going to leave it as it is, in the idea of changing as little as possible within this changeset. I think it could be something to revisit though!

2021-03-08 14:14 UTC, merged