CFIN-450 Make the accessibility tree course links be the course title and award
university-of-york/uoy-app-course-search pull request #114
Opened 2021-04-19 13:58 UTC by ncn1

The course links until this change have appeared in the accessibility tree with link text containing the course's title and all of its tags eg. 'Music - BA (Hons) Undergraduate BA (Hons) Start 2021 3 years full-time'

This change makes it 'Music - BA (Hons)'.

With grateful acknowledgement of Fergus's detailed notes on the JIRA story of how to tackle this.

2021-04-19 14:06 UTC, RichardAllum commented on src/tests/components/Course.test.js
> +        expect(screen.getByRole("link", { name: "A Course - Award" })).toBeInTheDocument();
The `getByRole` here is a touch confusing for me, does the `a` tag have an implicit `link` role. or is it granted to the `h2` by the `aria-labelledby` attribute?

2021-04-19 14:23 UTC, ncn1 commented on src/tests/components/Course.test.js
> +        expect(screen.getByRole("link", { name: "A Course - Award" })).toBeInTheDocument();
The a tag has an implicit link role.  Then the aria-labelledby is just telling it to use the heading bit for the aria label.

2021-04-20 10:15 UTC, FergusMcGlynn commented on src/components/Course.js
> +    const linkId = "course-title-" + title(course).replace(/ /g, "-");
I don't think course titles are unique - `Mathematics - BSc (Hons)` and `Mathematics - MMath (Hons)` have the same course title, `Mathematics`. This line of code would give them both the same `id`, which might things up for assistive tools. I think we should try to make the `id` unique for each course entry.

Also, v minor thing, the variable is called `linkId`, but it's actually used as an id for the `<h2>` heading rather than the link, so perhaps it should be `headingId`?

2021-04-20 10:18 UTC, FergusMcGlynn requested changes
I think we should try to make the new `id` unique for each course. Would combining title and award make a unique combination? Might be worth asking BAs or Digital Platforms perhaps?

2021-04-20 11:21 UTC, ncn1 commented on src/components/Course.js
> +    const linkId = "course-title-" + title(course).replace(/ /g, "-");
title(course) is referencing the function above, which includes the award in the title if there is one present - drawback of only being shown the changed code. Happy to change the id name.

2021-04-20 11:31 UTC, ncn1 commented
> I think we should try to make the new `id` unique for each course. Would combining title and award make a unique combination? Might be worth asking BAs or Digital Platforms perhaps?

It's already doing this - see response to comment.

2021-04-20 11:59 UTC, FergusMcGlynn approved these changes
Thanks Nicola - I didn't realise that the award was included in the return value from `title()`. Looks good!

2021-04-20 13:40 UTC, RichardAllum approved these changes

2021-04-23 08:34 UTC, merged