CFIN-317 Update documentation
university-of-york/uoy-app-course-search pull request #35
Opened 2020-10-06 15:04 UTC by ncn1

* add details of testing and its automation
* add automatic deployment details
* update details of code style checks to reflect changed workflows.

2020-10-06 15:30 UTC, mrgibbonsuoy approved these changes

2020-10-07 12:30 UTC, ce666-york approved these changes

2020-10-07 14:43 UTC, FergusMcGlynn requested changes
Only minor changes - but I think it'd be good to consolidate the two `Testing` sections into one.

2020-10-07 14:43 UTC, FergusMcGlynn commented on README.md
> +```
This sort of duplicates the `## Testing` section later on in the document. I think it'd be good to somehow consolidate the two sections into one - I don't mind whether it's here or in the other `Testing` section.

2020-10-08 08:39 UTC, ncn1 commented on README.md
> +```
Oops, I didn't actually spot the heading near the bottom, I e just expected it to be higher up like the Courses API one.

2020-10-08 08:54 UTC, RichardAllum approved these changes

2020-10-08 08:55 UTC, FergusMcGlynn approved these changes

2020-10-08 09:26 UTC, merged