CFIN 402 Create new tags
university-of-york/uoy-app-course-search pull request #78
Opened 2020-11-10 12:33 UTC by ncn1

For the purpose of being able to demo the styling etc, each course has 2 hard-coded tags for the extra details such as year abroad etc that are not currently being passed in the Courses API.

This has also necessitated some creativity with the tests, which I will comment on in situ

2020-11-10 12:33 UTC, ncn1 commented on src/components/CourseDetails.js
> +                title="Extras"
Hard-coded tags

2020-11-10 12:38 UTC, ncn1 commented on src/tests/components/CourseDetails.test.js
> +    });
This is the fiddle to ensure the test works with the hard-coded tags, in which case there will be some tags returned, and also when there are no hard-coded tags, so queryAllByRole("listitem") returns an empty array. Will need refactoring once design is finalised.

2020-11-10 13:19 UTC, mrgibbonsuoy approved these changes

2020-11-10 15:42 UTC, FergusMcGlynn commented on src/components/CourseDetails.js
> +                    { icon: "plane", text: "Distance Learning" },
Should the "Distance Learning" icon in this tag be consistent with the "Distance Learning" icon in the previous `ExtrasTag`?

2020-11-10 15:45 UTC, FergusMcGlynn commented on src/components/CourseDetails.js
> +                title="Extras"
Are these hard coded in order to demonstrate how they look? Presumably we don't want them present on every course result?

2020-11-10 15:50 UTC, FergusMcGlynn commented on src/components/CourseDetails.js
> +    const tag = level || award ? <Tag topIcon="mortar-board" title={level} subText={award} /> : null;
I find this line a little hard to parse - could we expand it to make it easier to read?

2020-11-10 15:53 UTC, FergusMcGlynn commented on src/components/Tag.js
> +    <div className="new-tag" role="listitem">
Is the class name `new-tag` for illustrative purposes? Fine if so, but if not I think it could be confusing.

2020-11-10 16:04 UTC, FergusMcGlynn commented on src/pages/_app.js
> +export default MyApp;
This is new to me - how does this relate to the new tags design?

2020-11-10 16:05 UTC, FergusMcGlynn commented on src/pages/_app.js
> +export default MyApp;
Also is `MyApp` the most appropriate name for this function? (It may well be - I don't understand the context enough to know - but it doesn't seem like a very descriptive name)

2020-11-10 16:33 UTC, ncn1 commented on src/components/CourseDetails.js
> +                    { icon: "plane", text: "Distance Learning" },
Yes - see introductory comment

2020-11-10 16:34 UTC, ncn1 commented on src/components/CourseDetails.js
> +                title="Extras"
Yes - see introductory comment

2020-11-10 16:34 UTC, RichardAllum commented on src/components/CourseDetails.js
> +                title="Extras"
They're just there for demoing, yeah. This PR isn't going into dev, so they'll be removed before that

2020-11-10 16:35 UTC, RichardAllum commented on src/components/CourseDetails.js
> +                    { icon: "plane", text: "Distance Learning" },
Maybe! It's entirely seeing if things exist at the moment

2020-11-10 16:35 UTC, ncn1 commented on src/components/CourseDetails.js
> +                    { icon: "plane", text: "Distance Learning" },
Would be less confusing, even though they are just here for demo purposes. I will change.

2020-11-10 16:38 UTC, ncn1 commented on src/components/CourseDetails.js
> +    const tag = level || award ? <Tag topIcon="mortar-board" title={level} subText={award} /> : null;
It's basically the equivalent of the Groovy elvis operator - if there is either a level or award, return something, else return nothing. It's a choice of this succinct one -liner or 6 lines of an if / else statement.

2020-11-10 16:38 UTC, RichardAllum commented on src/components/CourseDetails.js
>  };
```suggestion
const LevelAndAwardTag = ({ level, award }) => {
    if (level || award) {
        return <Tag topIcon="mortar-board" title={level} subText={award} />
    }
    return null;
};
```
per Ferg's comment above.

2020-11-10 16:40 UTC, FergusMcGlynn commented on src/tests/components/CourseDetails.test.js
> +        } else {
I don't understand this bit. Presumably `expect((tag.length = 0));` is doing nothing because it's assigning `0` to `tag.length`, and that's not something I'd expect to verify with `expect`. Can this be simplified to:
```suggestion
        if (tag.length > 0) {
```
(I don't know whether it can BTW)

Aside from the above - I think conditional checks in tests are a bit strange and I think we should avoid them. As you say, this is going to be refactored at some point. Although I wouldn't want it to be merged in to `dev` like this if we can avoid it.

2020-11-10 16:41 UTC, RichardAllum requested changes
I think we'll want to take the `Tag/ArrayTag` components and commit them to CFIN-371 in a brand new commit once the styles are in the pattern library

2020-11-10 16:41 UTC, ncn1 commented on src/components/CourseDetails.js
>  };
I think as we use the original style a bit more, it will become familiar and no longer difficult to parse. When learning Groovy, I found most of it's shortcuts difficult to read, but came to really like them as the language became familiar.

2020-11-10 16:45 UTC, ncn1 commented on src/pages/_app.js
> +export default MyApp;
It's code that needs to be included so you can include a local css file. I blindly followed some instructions, so I don't actually understand it myself. Hopefully we can remove it once the new styles are in the pattern library.

2020-11-10 16:45 UTC, FergusMcGlynn commented on src/tests/components/CourseSearchResults.test.js
> +        expect(headings[1]).toHaveTextContent("Physics");
Any particular reason for selecting these as headings as opposed to links? I appreciate that they are both, but from a user's perspective I would have thought it's more important that they are links than that they are headings.

2020-11-10 16:55 UTC, FergusMcGlynn commented on src/tests/components/TagList.test.js
> +        expect(tags[4]).toHaveTextContent("Integrated Masters");
It's a bit weird to the reader how we're jumping to the 5th element in the `tags` array. I'm guessing that's because we have lists within lists, and `getAllByRole('listitem')` is fetching every list item. It makes me wonder whether this would be confusing for a screen reader.

A possible alternative might be to use `<dl>`, `<dt>` and `<dd>` for the sub lists. `<dt>` has the implicit role `term` and `<dd>` has the implict role `definition`, so we'd be able to `getAllByRole('term')` or `getAllByRole('definition')` and that might be less confusing to a screen reader.

2020-11-10 16:55 UTC, FergusMcGlynn commented on src/tests/components/TagList.test.js
> +        expect((planes.length = 2));
I don't think `plane` is a good name for a test id

2020-11-10 16:58 UTC, FergusMcGlynn commented on src/components/CourseDetails.js
>  };
It's not clear what the operator precedence is in the original line - does the `||` take precedence, or does the `?`?

2020-11-10 17:00 UTC, FergusMcGlynn commented on src/components/CourseDetails.js
>  };
I prefer Richard's suggestion. It's not quite equivalent to the Groovy elvis operator because of the `||` - which is what justifies breaking it down.

2020-11-10 17:07 UTC, FergusMcGlynn commented on src/tests/components/CourseDetails.test.js
> +        expect(tag[0]).not.toHaveTextContent("BA (Hons)");
I find this line (`.not.toHaveTextContent("BA (Hons)")`) a bit arbitrary. It might as well say `.not.toHaveTextContent("banana")`. If the goal is to verify that only the text `undergraduate` is presented and no other text whatsoever then I suspect there's a more robust way to verify it.

2020-11-10 17:12 UTC, FergusMcGlynn commented on src/tests/components/CourseDetails.test.js
> +        expect(tag[0]).not.toHaveTextContent("BA (Hons)");
Looks like you can use [a regular expression inside `toHaveTextContent`](https://github.com/testing-library/jest-dom#tohavetextcontent) - that could be a way of verifying that exactly `undergraduate` is matched and there's no other text:

```
expect(tag[0]).toHaveTextContent(/^undergraduate$/);
```

2020-11-10 17:20 UTC, FergusMcGlynn requested changes
I'm not quite sure how much of this PR is demo-ing ideas and how much of it is intended to be merged into `dev`, so I feel conflicted about whether or not to `Request changes`. I'll do so, to reflect that I think some tests could be improved, in line with the comments I've left. Apologies if that's not keeping in the spirit of this PR!

2020-11-11 09:58 UTC, FergusMcGlynn commented
As an aside - it might be worth marking this PR as a "draft", if its purpose is to showcase some changes without requesting the full scrutiny of a code review. I'm still not entirely clear what level of reviewing is being requested.

2020-11-12 10:20 UTC, ncn1 commented on src/components/CourseDetails.js
> +    const tag = level || award ? <Tag topIcon="mortar-board" title={level} subText={award} /> : null;
Fergus, can I not persuade you to embrace the terniary operator for single if - then - else 's like this one? https://www.javascripttutorial.net/javascript-ternary-operator/ . I think nesting them gets very hard to follow, but I think single ones do remove a lot of verbosity.

2020-11-12 10:26 UTC, ncn1 commented on src/components/CourseDetails.js
> +    const tag = level || award ? <Tag topIcon="mortar-board" title={level} subText={award} /> : null;
Sorry, did not see your reply to the other thread before adding my previous comment.

2020-11-12 10:29 UTC, FergusMcGlynn commented on src/components/CourseDetails.js
> +    const tag = level || award ? <Tag topIcon="mortar-board" title={level} subText={award} /> : null;
I'm fine with ternary operators for simple `if a then b else c` expressions, but this one is a bit more complicated than that. Is it saying 
```
level || (award ? <Tag ... /> : null)
```
or
```
(level || award) ? <Tag .../> : null
```
? It's not immediately obvious to me. Also I think one of the sub-expressions being JSX makes it a bit trickier to parse than a simple all-javascript ternary. 

Richard suggested an alternative which makes it really easy to parse, and it's only a couple of lines. I'm not going to die in a ditch over it, and if everyone else finds the ternary perfectly easy to understand then we can stick with it.

2020-11-12 10:31 UTC, ncn1 commented on src/components/CourseDetails.js
>  };
Annoyingly, if I put brackets around 'level || award' in the terniary version, Prettier removes them!

2020-11-12 11:05 UTC, ncn1 commented on src/tests/components/CourseDetails.test.js
> +        expect(tag[0]).not.toHaveTextContent("BA (Hons)");
Thanks - much better way of doing it.

2020-11-12 11:21 UTC, ncn1 commented on src/tests/components/TagList.test.js
> +        expect(tags[4]).toHaveTextContent("Integrated Masters");
Description lists are only supposed to have 1 <dd> element, whereas our Extras tab needs there to be multiple lines under the <dt>. So standard lists it needed to be. I agree it isn't great - I keep coming up against the need for a getByClass option, but this has so far been ruled out by the authors of the testing library.

2020-11-12 11:23 UTC, ncn1 commented on src/tests/components/TagList.test.js
> +        expect((planes.length = 2));
It means it can be the same as the icon name. Again, class name would have been much simpler to use here, and negate the need for a test id.

2020-11-12 12:20 UTC, ncn1 commented on src/tests/components/CourseSearchResults.test.js
> +        expect(headings[1]).toHaveTextContent("Physics");
Yes, the name of the links now also includes all the text in the tags.

2020-11-12 12:22 UTC, FergusMcGlynn commented on src/tests/components/CourseSearchResults.test.js
> +        expect(headings[1]).toHaveTextContent("Physics");
Isn't that potentially an accessibility problem? If a screen reader is going to read out everything for a link? This might need some thought.

2020-11-12 12:32 UTC, ncn1 commented on src/tests/components/CourseSearchResults.test.js
> +        expect(headings[1]).toHaveTextContent("Physics");
I think that should be left for CFIN-401 'Ensure accessibility of new tags' to check and address if necessary. I has assumed it was just a React testing library artifact.

2020-11-12 14:21 UTC, FergusMcGlynn commented on src/tests/components/CourseSearchResults.test.js
> +        expect(headings[1]).toHaveTextContent("Physics");
Fair enough - so long as it's not forgotten

2020-11-12 14:31 UTC, ncn1 commented
> I'm not quite sure how much of this PR is demo-ing ideas and how much of it is intended to be merged into `dev`, so I feel conflicted about whether or not to `Request changes`. I'll do so, to reflect that I think some tests could be improved, in line with the comments I've left. Apologies if that's not keeping in the spirit of this PR!

It was a bit of both, and the code review has been really helpful. But if you are now ok with the changes that have already been made and knowing that it will not go into dev like this (and that would require another pull request, anyway, as this is just merging into the story branch) would you be able to approve it now?

2020-11-12 14:36 UTC, FergusMcGlynn approved these changes

2020-11-12 15:03 UTC, ncn1 commented
As Richard has pointed out, probably best not to merge these changes into the story branch, as all the hard-coding and tests that account for the hard-coding will need removing before merging into dev, so closing the PR without merging.

2020-11-12 15:03 UTC, closed without merging