CFIN-261 Add Prettier
university-of-york/uoy-app-course-search pull request #8
Opened 2020-09-15 11:18 UTC by ncn1

After a bit of discussion on the esg-developers channel on Slack, I decided to mainly stick with Prettier's defaults apart from printwidth of 100 (ie. where it inserts line breaks) and tabwidth, which I made 4 for most things but 2 for .yml and .json files. I have also set it to ignore publish-c4-model.yml, as it's not part of the main app and I don't want to risk it messing up working code.

Also, using Prettier has changed CRLF line feeds to LF  - so if you can't see what's changed, that is likely to be it.

2020-09-16 13:37 UTC, FergusMcGlynn requested changes

2020-09-16 13:37 UTC, FergusMcGlynn commented on src/tests/pages/index.test.js
> +    // prettier-ignore
I tried this out locally (removed the `// prettier-ignore` comment, then ran `prettier` on the file) and the only lines that prettier changed was converting 
```
expect(
    screen.getByRole("heading", { name: "Hello World!" })
).toBeInTheDocument();
```
into 
```
expect(screen.getByRole("heading", { name: "Hello World!" })).toBeInTheDocument();
```
Everything else about the test file stayed the same. Personally, I'm fine with the change that `prettier` made - that's how all of our tests in the Proposals app were formatted. 

If we're going to use an opinionated code formatter like Prettier then I think we'll need to accept that sometimes it will format things in a way that we might not choose to do ourselves. The key is that it will format code consistently. We should avoid overriding it on individual cases unless it does something truly intolerable (and then I think we should be looking at the global overrides as a first step). So I'd advocate removing `// prettier-ignore` and letting it make the change here.

2020-09-17 08:58 UTC, RichardAllum commented on .prettierrc.json
> +    "printWidth": 100,
A larger line length could be the solution, and I think it may just be my personal preferences - if you have a semi-complex DOM structure indents can take up a lot of width for markup, and you can end up with components that look a bit like
```                                      <div
                                             className="
                                             class1
                                             class2">
                                             {content}
                                          </div> ```
And it gets hard to distinguish what classes/content/tags are. I'd be happy with trying this out until we encounter these problems though.

2020-09-17 14:15 UTC, FergusMcGlynn approved these changes

2020-09-17 14:30 UTC, merged