CFIN-390 Local performance testing scripts
university-of-york/uoy-app-course-search pull request #87
Opened 2020-11-23 09:53 UTC by ChristianBeddows

2020-11-23 10:50 UTC, ncn1 commented
> You'll need to be running a production server on port 3000 prior to the run for this to work.

ie. run the 'prod' npm script

2020-11-23 10:51 UTC, FergusMcGlynn approved these changes
I've run this locally and it seems to work fine for both desktop and mobile. I get really bad scores for desktop, but that's another ticket.

2020-11-23 10:53 UTC, ncn1 approved these changes

2020-11-23 11:46 UTC, ce666-york commented on package.json
> +    "prod": "npm run build && npm run start",
Does this use development or production environment variables? Wondering if it's slightly misnamed and better to just roll into `start`

2020-11-23 11:50 UTC, FergusMcGlynn commented on package.json
> +    "prod": "npm run build && npm run start",
It'll be running production environment variables

2020-11-23 11:59 UTC, ce666-york commented on package.json
> +    "prod": "npm run build && npm run start",
Thanks Ferg. I think in my head there's a slightly separate (and wider) issue of local environment variables, when you might expect to use them, and what our defaults are. This also ties into the question of ideally how would we want to develop locally, as currently there's a dependency on the development or production API.

2020-11-23 12:13 UTC, ce666-york requested changes
These scripts seem to give significantly worse performance scores for both desktop (mid 60's) and mobile (mid 30's) compared to what running Lighthouse in Chrome/Pagespeed insights give (mid 90's for desktop and mid 60's for mobile).

I think we need to work out why this is the case before we can use these scripts - looks great so far but I think there's a bit more to do!

2020-11-23 12:13 UTC, ce666-york approved these changes
(Should have marked as approved as in principle I think these changes are fine to be merged!)

2020-11-23 12:16 UTC, ce666-york requested changes
Actually I think this PR should be for merging into the story branch `CFIN-140` rather than `dev`. It'll probably be good to merge `CFIN-140` back into your branch too so you can develop against the build with the performance improvements.

2020-11-24 14:32 UTC, mrgibbonsuoy approved these changes

2020-11-26 11:21 UTC, ChristianBeddows commented
I'm closing this PR as I need to do some git tidying, and further changes to get the script working at an acceptable level.

2020-11-26 11:21 UTC, closed without merging