CFIN-402 Create new rich tags
university-of-york/uoy-app-course-search pull request #96
Opened 2021-01-19 10:31 UTC by ncn1

2021-01-19 14:42 UTC, FergusMcGlynn commented on src/components/RichTag.js
> +            {title && <dt className="rich-tag__title">{title}</dt>}
A `<dt>` is [supposed to sit within a description list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dt) (`<dl>` tag) - is `<dt>` the appropriate tag for this situation?

2021-01-19 14:50 UTC, FergusMcGlynn commented on src/tests/components/CourseDetails.test.js
> +    /* Commenting out the following test until the hard-coded extras tags are removed */
You can ignore tests by adding `.skip` to the keyword `it`, `test` or `describe`, e.g. 
```
it.skip("works with no metadata", () => {
```
But I would prefer it if we didn't comment out or ignore any tests. Is there any particular reason why `the hard-coded extras tags are removed` can't be done as part of this work?

2021-01-19 14:52 UTC, FergusMcGlynn commented on src/components/RichTag.js
> +const ArrayTag = ({ title, content }) => {
I can't see anywhere that this function is being used. Is it needed?

2021-01-19 14:56 UTC, FergusMcGlynn commented on src/pages/_app.js
> +export default MyApp;
I think this came up in the last PR for this code. `MyApp` doesn't seem like a production-grade function name to me. I also don't really understand what it's doing. I think last time you said that it had been copied and pasted from a website to make something work. It'd be good to see if we can get an understanding of how/why it works, as we'll be maintaining it.

2021-01-19 15:05 UTC, ncn1 commented on src/components/RichTag.js
> +const ArrayTag = ({ title, content }) => {
Part of the problem with this being designed for moving to the pattern library. ArrayTag is for the extras tag, which had demo versions and these have been removed. I don't think we are planning to use the extras tags in the first release. But they will be needed somewhere eventually.

2021-01-19 16:24 UTC, FergusMcGlynn commented on src/components/RichTag.js
> +const ArrayTag = ({ title, content }) => {
If we're not going to use `ArrayTag` and `ArrayTagContents` in the first release then I think we should remove the code.

2021-01-19 16:31 UTC, FergusMcGlynn commented on src/components/CourseDetails.js
> +            <LevelAndAwardTag level={course.level} award={course.award} />
Do we need to tidy up the case of `course.level`? By default, I'm guessing this will output "undergraduate" for all undergraduate courses - but in the designs, it states "Undergraduate".

2021-01-19 16:38 UTC, FergusMcGlynn commented on src/tests/components/CourseDetails.test.js
> +    it("displays level and award tag when both only level is present", () => {
Test name needs a little tidying
```suggestion
    it("displays level and award tag when only level is present", () => {
```

2021-01-19 16:41 UTC, ncn1 commented on src/components/CourseDetails.js
> +            <LevelAndAwardTag level={course.level} award={course.award} />
The css takes care of it.

2021-01-19 16:42 UTC, FergusMcGlynn commented on src/tests/components/CourseDetails.test.js
> +        }
I'm confused by this `if`/`else` - it's a bit odd to see a conditional in a test, and I'm not really sure what it's achieving here.

2021-01-19 16:48 UTC, FergusMcGlynn commented on src/tests/components/CourseSearchResults.test.js
> +        expect(headings[1]).toHaveTextContent("Physics");
Any particular reason for switching from `link` role to `heading` role for these tests?

2021-01-19 16:52 UTC, FergusMcGlynn commented on src/tests/components/RichTagList.test.js
> +    it("displays extra tags as per inputs", () => {
I think we can delete this test, or move it to a branch where 'extras' tag work can be stashed, if the 'extras' tag isn't required in the first release.

2021-01-19 16:54 UTC, FergusMcGlynn commented on src/tests/pages/index.test.js
> +        expect(headings[3]).toHaveTextContent("Physics");
Similar to another file - is there any particular reason to select by the `heading` role rather than the `link` role here? Referring to `headings[2]` and `headings[3]` isn't particularly intuitive to a newcomer.

2021-01-19 17:04 UTC, FergusMcGlynn commented on styles.css
> +    text-transform: capitalize;
This should be fine for the tag content that we want to display in the first release. We might need to change it in future though - a tag for "Year in Industry" would be transformed to "Year In Industry" by this. Also "Available for clearing" would become "Available For Clearing". Do we want to cross that bridge when we come to it, or deal with it now?

2021-01-19 17:07 UTC, FergusMcGlynn requested changes
There are a couple of issues where I've commented that I think it'd be good to resolve before merging.

2021-01-20 14:24 UTC, RichardAllum commented on src/components/RichTag.js
> +            {title && <dt className="rich-tag__title">{title}</dt>}
Good spot, this should be either a `<div>`, a `<p>` or a `<span>` - this will be left in from where we tried using a description list but found it didn't work with icons

2021-01-20 14:25 UTC, ncn1 commented on src/tests/components/CourseDetails.test.js
> +    /* Commenting out the following test until the hard-coded extras tags are removed */
They have been removed - I will reinstate this test

2021-01-20 14:29 UTC, ncn1 commented on src/tests/components/CourseDetails.test.js
> +        }
Another leftover from the demo tags

2021-01-20 14:38 UTC, ncn1 commented on src/tests/pages/index.test.js
> +        expect(headings[3]).toHaveTextContent("Physics");
It's a more specific test - these items are headings and come in this order.

2021-01-20 14:41 UTC, ncn1 commented on styles.css
> +    text-transform: capitalize;
I think it looks OK https://uoy.enterprise.slack.com/files/W013GPC4T7G/F01J7NLTY22/image.png, 
so only change it later if someone specifically notices and objects to "Year In Industry"

2021-01-20 16:12 UTC, ncn1 commented on src/tests/components/CourseSearchResults.test.js
> +        expect(headings[1]).toHaveTextContent("Physics");
Allows for the testing of the order they appear in as well as the fact they do appear.

2021-01-21 16:58 UTC, FergusMcGlynn commented on styles.css
> +    text-transform: capitalize;
I think "Year In Industry" and "Available For Clearing" might not conform to the [University style guide](https://www.york.ac.uk/staff/external-relations/print-marketing/style/). Under "capitalisation" it says
```
Do not capitalise:
    * the smaller words in titles such as in, at, of, the, and, on
````
It also links to the [digital content style guide](https://wiki.york.ac.uk/display/DM/Digital+content+style+guide), which has a note about [capitalisation of headings](https://wiki.york.ac.uk/pages/viewpage.action?pageId=74712085):
```
All headings and navigation should be written in sentence case
```
I realise these are not headings - so maybe the rule doesn't apply here. I think it might be worth querying. It would be a bit odd to forbid (for example) "4 Years Full-Time" in a heading, but permit it in a rich-tag/key-fact. I'll post something in Slack and see what others think.

2021-01-21 17:07 UTC, FergusMcGlynn commented on src/tests/pages/index.test.js
> +        expect(headings[3]).toHaveTextContent("Physics");
The specific ordering improvement comes from the `getAllBy...` (instead of `getBy...`), not because we've switched from selecting links to selecting headings. From a user's perspective, I'd have thought it's more important that there's a link to a course page (with descriptive link text) than that there's a heading with a course's title in it.

I've also just found, in the [University's digital style guide](https://wiki.york.ac.uk/pages/viewpage.action?pageId=74712085#Style(contentpatterns)-Headingsandsub-headings), the following:
```
Don't put links in headings
```
This is news to me, and I'll post something in Slack for the team to discuss - I don't think we need to resolve that in this PR. It might not be relevant because, technically, we're putting a heading in a link, but there might be a style principle here that we need to consider. It makes me even more wary of testing by heading rather than testing by link

2021-01-21 17:11 UTC, FergusMcGlynn commented on src/tests/pages/index.test.js
> +        expect(headings[3]).toHaveTextContent("Physics");
Also, regarding the point about `headings[2]` and `headings[3]`, it's a bit confusing for a reader - where are `headings[0]` and `headings[1]`? Why is `2` a magic number? I'm guessing that `headings[0]` refers to the `<h1>` page title and `headings[1]` refers to... some other heading somewhere, but it's not intuitive. The reader needs to know some things that are outside the test in order to understand the test.

2021-01-22 14:58 UTC, FergusMcGlynn commented on styles.css
> +    text-transform: capitalize;
From what Paul Kelly has posted in Slack, it looks like we should be aiming for `4 years full-time` rather than `4 Years Full-Time`. It doesn't look like there's a CSS `text-transform` value for sentence case, but I found [a potential workaround](https://css-tricks.com/almanac/properties/t/text-transform/#comment-1607495) online. It might need some tweaking, but maybe worth a try?

2021-01-25 09:33 UTC, ncn1 commented on styles.css
> +    text-transform: capitalize;
Good find!

2021-01-25 09:59 UTC, FergusMcGlynn commented on styles.css
> +}
Is there any way we can test this? It'd be nice to be able to verify that this does what we're intending.

2021-01-25 11:09 UTC, ncn1 commented on styles.css
> +}
I think only by viewing the Percy snapshot. In CourseDetails.test.js, it was passing this test "displays tag with start year and length of course when both are present" which contains `expect(tag[0]).toHaveTextContent("4 years full-time");` when it was actually showing as '4 Years Full-Time'

2021-01-25 11:16 UTC, FergusMcGlynn commented on styles.css
> +}
Maybe something like Cypress could test this? We've been talking for a while about investigating Cypress testing (which I believe would be akin to Geb tests for a Grails application). This might a be a good opportunity to see whether that's a worthwhile option, if there's no way of testing CSS changes using React Testing Library?

2021-01-25 11:20 UTC, ChristianBeddows approved these changes

2021-01-25 11:23 UTC, ChristianBeddows commented on styles.css
> +}
Interesting - `toHaveTextContent` should be case sensitive

![Screenshot from 2021-01-25 11-21-29](https://user-images.githubusercontent.com/17494696/105699703-b28a1f80-5eff-11eb-8867-45d30233934b.png)

2021-01-25 11:24 UTC, ChristianBeddows commented on styles.css
> +}
Although thinking about it - if the CSS is doing the capitalising, then it's text content was always `4 years full-time` - which might explain why it was passing! Would it be possible to use a `.toBeDisplayed` method to ensure it's viewable as we expect?

2021-01-25 11:29 UTC, ChristianBeddows commented on styles.css
> +}
I notice there's a method called `getByDisplayValue` - perhaps this would take the CSS capitalisation into account?

![Screenshot from 2021-01-25 11-28-49](https://user-images.githubusercontent.com/17494696/105700260-83c07900-5f00-11eb-9b03-6f5373b314f6.png)

2021-01-25 11:31 UTC, FergusMcGlynn commented on styles.css
> +}
Richard's right that text-transform [doesn't change the DOM](https://github.com/testing-library/react-testing-library/issues/567). I disagree though that we'd just be testing standard CSS - we'd be testing whether or not we're using it correctly to achieve what we want to achieve.

2021-01-25 11:33 UTC, ncn1 commented on styles.css
> +}
I think that investigating Cypress testing is beyond the scope of this story and PR, (which is beginning to seem never ending!) The Percy test has caught the fact that the page did change as a result of this css change, and I in fact thought that was the point of adding Percy, to detect changes made by css that not easily testable with the React testing library.

2021-01-25 11:44 UTC, RichardAllum commented on styles.css
> +}
I think Cypress testing may be worth adding to this project at some point, but I also don't think this PR is the place to start - the text capitalisation is not in the acceptance criteria, and adding a new testing framework to the project for it at the final hurdle feels like overkill to me. I'd be happy to put a story in the backlog for Cypress testing on a more generic level though, as there would be user benefit to it.

2021-01-25 11:47 UTC, FergusMcGlynn commented on styles.css
> +}
I see Percy as being more a safety check to ensure that a code change hasn't introduced an unintended UI change. I wouldn't even call Percy a "test" - it's a check, it can't validate that the application delivers on its requirements.

We have a requirement - "text in tags should be presented in sentence case". We have input data, from the Courses API. We can write a test that verifies whether, no matter what the input data is, the output is presented in sentence case. This is testable and, if not crazy amounts of effort, worth testing, as are all requirements of the application.

It may be that it would take crazy amounts of effort to do such a test, in which case we might decide that we don't have the resources to do it. But I don't think it's quite right to say that Percy is capable of validating this requirement.

2021-01-25 11:59 UTC, ce666-york commented on styles.css
> +}
I also see visual testing as an aid or a prompt rather than a substitute for functional tests.

I've been wanting us to look into Cypress for a while, I don't mind being flexible and including it in this story, but if it's a lot of work happy to split it out too. Reading the docs, it does sound interesting and quite straightforward https://docs.cypress.io/guides/getting-started/writing-your-first-test.html.

2021-01-25 12:00 UTC, FergusMcGlynn commented on styles.css
> +}
Agreed that "the text capitalisation is not in the acceptance criteria" - but that's an argument for not implementing a text capitalisation solution. I don't see it as an argument for not testing a text capitalisation solution. Too many "not"s - but I hope you see what I mean.

2021-01-25 12:31 UTC, closed without merging